# Generated by Django 4.1 on 2022-09-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='step_thumbnail',
            field=models.ImageField(default=None, help_text='Pridajte thumbnail', upload_to='static/photos/<django.db.models.fields.CharField>/thumbnail.jpg'),
        ),
    ]
