# Generated by Django 4.1 on 2022-09-18 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0002_alter_rating_recipe_instance_alter_recipe_attributes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientinstance',
            old_name='recipe',
            new_name='recipe_version',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='recipe_instance',
            new_name='recipe_version',
        ),
        migrations.CreateModel(
            name='DeliveryInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dátum')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Čas vzniku')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Naposledy upravené')),
                ('normal_recipes', models.ManyToManyField(related_name='usages', through='recepty.Rating', to='recepty.recipeversion', verbose_name='Obyčajné recepty')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='delivery_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recepty.deliveryinstance'),
        ),
    ]
