# Generated by Django 4.1 on 2022-09-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0002_recipe_step_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='step_thumbnail',
            field=models.ImageField(default=None, help_text='Pridajte thumbnail', upload_to='recepty/static/photos/'),
        ),
    ]
