# Generated by Django 4.1 on 2022-09-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0003_alter_recipe_step_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Názov ingrediencie', max_length=31, unique=True)),
                ('price_per_unit', models.FloatField()),
                ('unit', models.CharField(choices=[('', 'Zvolte jednotku'), ('g', 'gramy'), ('ml', 'mililitre')], max_length=3)),
            ],
        ),
    ]
