# Generated by Django 4.1 on 2022-09-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0003_rename_recipe_ingredientinstance_recipe_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, choices=[('1', 'Porcia bola malá'), ('2', 'Porcia mohla byť trochu väčšia'), ('3', 'Porcia bola akurát'), ('4', 'Stačilo by trochu menej'), ('5', 'Porcia bola príliš veľká')], default=None, help_text='Sedelo množstvo jedla s objednanou porciou?', max_length=1, null=True, verbose_name='Hodnotenie množstva')),
                ('taste', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, help_text='Viac je lepšie', max_length=1, null=True, verbose_name='Chuť')),
                ('delivery', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, help_text='Viac je lepšie', max_length=1, null=True, verbose_name='Doručenie')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Čas vzniku')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Naposledy upravené')),
            ],
        ),
        migrations.AlterField(
            model_name='deliveryinstance',
            name='normal_recipes',
            field=models.ManyToManyField(related_name='usages', through='recepty.RecipeInstance', to='recepty.recipeversion', verbose_name='Obyčajné recepty'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='recipeinstance',
            name='delivery_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recepty.deliveryinstance'),
        ),
        migrations.AddField(
            model_name='recipeinstance',
            name='recipe_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='recepty.recipeversion'),
        ),
    ]
