# Generated by Django 4.1 on 2022-09-18 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0004_recipeinstance_alter_deliveryinstance_normal_recipes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryinstance',
            name='normal_recipes',
        ),
        migrations.AddField(
            model_name='deliveryinstance',
            name='recipes',
            field=models.ManyToManyField(related_name='usages', through='recepty.RecipeInstance', to='recepty.recipeversion', verbose_name='Recepty'),
        ),
        migrations.AlterField(
            model_name='recipeinstance',
            name='delivery_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recepty.deliveryinstance'),
        ),
        migrations.AlterField(
            model_name='recipeinstance',
            name='recipe_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='recepty.recipeversion', verbose_name='Recept'),
        ),
    ]
