# Generated by Django 4.1 on 2022-09-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0004_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price_per_unit',
            field=models.FloatField(help_text='Zadajte cenu na nižšie zvolenú jednotku', verbose_name='Cena na jednotku'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('', 'Zvolte jednotku'), ('g', 'gramy'), ('ml', 'mililitre')], help_text='Zvolte jednotku', max_length=3, verbose_name='Jednotka'),
        ),
    ]
