# Generated by Django 4.1 on 2022-09-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0005_remove_recipe_ingredients_remove_recipe_prep_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='recepty.recipeversion')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, help_text='Hodnotenie velkosti porcie', max_length=1, verbose_name='Množstvo')),
                ('taste', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, help_text='Hodnotenie chuti', max_length=1, verbose_name='Chuť')),
                ('delivery', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, help_text='Hodnotenie doručenia', max_length=1, verbose_name='Doručenie')),
                ('recipe_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recepty.recipeinstance')),
            ],
        ),
    ]
