# Generated by Django 4.1 on 2022-09-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0005_remove_deliveryinstance_normal_recipes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinstance',
            name='delivery_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recepty.deliveryinstance', verbose_name='Rozvoz'),
        ),
        migrations.AlterField(
            model_name='recipeinstance',
            name='recipe_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recepty.recipeversion', verbose_name='Recept'),
        ),
    ]
