# Generated by Django 4.1 on 2022-09-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0006_recipe_ingredients_alter_ingredient_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='step_thumbnail',
            new_name='thumbnail',
        ),
    ]
