# Generated by Django 4.1 on 2022-09-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0006_recipeinstance_rating'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='step',
            name='Each recipe has a unique set of steps',
        ),
    ]
