# Generated by Django 4.1 on 2022-09-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0006_alter_recipeinstance_delivery_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinstance',
            name='amount',
            field=models.CharField(blank=True, choices=[('1', 'Porcia bola malá'), ('2', 'Porcia mohla byť trochu väčšia'), ('3', 'Porcia bola akurát'), ('4', 'Stačilo by trochu menej'), ('5', 'Porcia bola príliš veľká')], default=None, help_text='Sedelo množstvo jedla s objednanou porciou?', max_length=1, verbose_name='Hodnotenie množstva'),
        ),
        migrations.AlterField(
            model_name='recipeinstance',
            name='delivery',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, help_text='Viac je lepšie', max_length=1, verbose_name='Doručenie'),
        ),
        migrations.AlterField(
            model_name='recipeinstance',
            name='taste',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, help_text='Viac je lepšie', max_length=1, verbose_name='Chuť'),
        ),
    ]
