# Generated by Django 4.1 on 2022-09-19 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_recipeorderinstance_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepty', '0007_alter_recipeinstance_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dátum')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Čas vzniku')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Naposledy upravené')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeOrderInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions', models.IntegerField(verbose_name='Množstvo porcií')),
                ('amount', models.CharField(blank=True, choices=[(None, 'Vyhovovala vám porcia'), ('1', 'Porcia bola malá'), ('2', 'Porcia mohla byť trochu väčšia'), ('3', 'Porcia bola akurát'), ('4', 'Stačilo by trochu menej'), ('5', 'Porcia bola príliš veľká')], default=None, help_text='Sedelo množstvo jedla s objednanou porciou?', max_length=1, verbose_name='Hodnotenie množstva')),
                ('taste', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, help_text='Viac je lepšie', max_length=1, verbose_name='Chuť')),
                ('delivery', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, help_text='Viac je lepšie', max_length=1, verbose_name='Doručenie')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.order')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipeinstance',
            name='delivery_instance',
        ),
        migrations.RemoveField(
            model_name='recipeinstance',
            name='recipe_version',
        ),
        migrations.RemoveField(
            model_name='recipeversion',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='step',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='step',
            name='step',
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Zvolte seba', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Profesional')], default=1, help_text='Zadajte náročnosť', verbose_name='Náročnosť'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='gluten_free',
            field=models.BooleanField(default=False, verbose_name='Gluten Free'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pescetarian',
            field=models.BooleanField(default=False, verbose_name='Pescetarian'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(default=25, help_text='Zadajte dĺžku prípravy', verbose_name='Čas prípravy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='vegan',
            field=models.BooleanField(default=False, verbose_name='Vegan'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vegetarian',
            field=models.BooleanField(default=False, verbose_name='Vegetarian'),
        ),
        migrations.AddField(
            model_name='step',
            name='text',
            field=models.TextField(default='text', help_text='Krok', max_length=250, verbose_name='Opis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[(None, 'Zvolte jednotku'), ('g', 'gramy'), ('ml', 'mililitre'), ('ks', 'kusy')], help_text='Zvolte jednotku', max_length=3, verbose_name='Jednotka'),
        ),
        migrations.AlterField(
            model_name='recipeversion',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='recepty.recipe'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_img',
            field=models.ImageField(help_text='Pridajte obrazok ku kroku', upload_to='recepty/static/photos/', verbose_name='Obrázok'),
        ),
        migrations.DeleteModel(
            name='DeliveryInstance',
        ),
        migrations.DeleteModel(
            name='RecipeInstance',
        ),
        migrations.AddField(
            model_name='recipeorderinstance',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepty.recipeversion'),
        ),
        migrations.AddField(
            model_name='deliveryday',
            name='recipes',
            field=models.ManyToManyField(help_text='Zvolte, ktoré recepty budú v daný deň na výber', related_name='delivery_days', to='recepty.recipeversion', verbose_name='Recepty na výber'),
        ),
    ]
