# Generated by Django 4.1 on 2022-09-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0007_remove_step_each recipe has a unique set of steps'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('recipe', 'step_no'), name='unique_step_number'),
        ),
    ]
