# Generated by Django 4.1 on 2022-09-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0007_rename_step_thumbnail_recipe_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergen',
            fields=[
                ('title', models.CharField(max_length=63, verbose_name='Alergén')),
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Kód alergénu')),
            ],
        ),
    ]
