# Generated by Django 4.1 on 2022-09-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0008_deliveryday_recipeorderinstance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='step_no',
            new_name='no',
        ),
        migrations.RemoveField(
            model_name='step',
            name='step_img',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='img',
            field=models.ImageField(blank=True, default=None, help_text='Pridajte obrazok ku kroku', null=True, upload_to='recepty/static/photos/', verbose_name='Obrázok'),
        ),
        migrations.AddField(
            model_name='step',
            name='img',
            field=models.ImageField(blank=True, default=None, help_text='Pridajte obrazok ku kroku', null=True, upload_to='recepty/static/photos/', verbose_name='Obrázok'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, help_text='Pridajte thumbnail', null=True, upload_to='recepty/static/photos/'),
        ),
    ]
