# Generated by Django 4.1 on 2022-09-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0008_alergen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='alergens',
            field=models.ManyToManyField(blank=True, help_text='Zvolte všetky alergény:', related_name='ingredients', to='recepty.alergen', verbose_name='Alergény'),
        ),
    ]
