# Generated by Django 4.1 on 2022-09-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0008_step_unique_step_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='step',
            name='unique_step_number',
        ),
    ]
