# Generated by Django 4.1 on 2022-10-02 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_userprofile_country'),
        ('recepty', '0009_rename_step_no_step_no_remove_step_step_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryday',
            name='recipes',
            field=models.ManyToManyField(blank=True, help_text='Zvolte, ktoré recepty budú v daný deň na výber', related_name='delivery_days', to='recepty.recipeversion', verbose_name='Recepty na výber'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='img',
            field=models.ImageField(blank=True, default=None, help_text='Pridajte obrazok ku kroku', null=True, upload_to='ingredients', verbose_name='Obrázok'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, help_text='Pridajte thumbnail', null=True, upload_to='recipes'),
        ),
        migrations.AlterField(
            model_name='recipeorderinstance',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_instance', to='home.order'),
        ),
        migrations.AlterField(
            model_name='recipeorderinstance',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_instance', to='recepty.recipeversion'),
        ),
        migrations.AlterField(
            model_name='step',
            name='img',
            field=models.ImageField(blank=True, default=None, help_text='Pridajte obrazok ku kroku', null=True, upload_to='steps', verbose_name='Obrázok'),
        ),
    ]
