# Generated by Django 4.1 on 2022-09-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0009_remove_step_unique_step_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientinstance',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientinstance',
            name='amount',
            field=models.IntegerField(help_text='Zadajte množstvo danej potraviny', verbose_name='Množstvo'),
        ),
    ]
