# Generated by Django 4.1 on 2022-10-02 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_order_recipes'),
        ('recepty', '0012_alter_recipeorderinstance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeorderinstance',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_instance', to='home.order'),
        ),
    ]
