# Generated by Django 4.1 on 2022-10-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_order_pickup'),
        ('recepty', '0013_alter_recipeorderinstance_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeorderinstance',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_instance', to='home.order'),
        ),
    ]
