# Generated by Django 4.1 on 2022-10-09 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0014_alter_recipeorderinstance_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinstance',
            name='recipe_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_mid', to='recepty.recipeversion'),
        ),
    ]
