# Generated by Django 4.1 on 2022-09-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0014_ingredient_date_created_ingredient_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Čas vzniku'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Naposledy upravené'),
        ),
        migrations.AlterField(
            model_name='recipeinstance',
            name='date_to_be_used',
            field=models.DateField(),
        ),
    ]
