# Generated by Django 4.1 on 2022-09-07 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0015_rating_date_created_rating_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Steps', to='recepty.recipeversion'),
        ),
    ]
