# Generated by Django 4.1 on 2022-09-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0016_alter_step_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktívny'),
        ),
        migrations.AlterField(
            model_name='recipeversion',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktívny'),
        ),
    ]
