# Generated by Django 4.1 on 2022-09-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0017_alter_recipe_active_alter_recipeversion_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeversion',
            name='steps',
            field=models.ManyToManyField(blank=True, help_text='Pridajte kroky', related_name='recipes', to='recepty.step', verbose_name='Kroky'),
        ),
    ]
