# Generated by Django 4.1 on 2022-09-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0018_alter_recipeversion_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recepty.recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='amount',
            field=models.CharField(blank=True, choices=[('1', 'Porcia bola malá'), ('2', 'Porcia mohla byť trochu väčšia'), ('3', 'Porcia bola akurát'), ('4', 'Stačilo by trochu menej'), ('5', 'Porcia bola príliš veľká')], default=None, help_text='Sedelo množstvo jedla s objednanou porciou?', max_length=1, null=True, verbose_name='Hodnotenie množstva'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='delivery',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, help_text='Viac je lepšie', max_length=1, null=True, verbose_name='Doručenie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='recipe_instance',
            field=models.ForeignKey(limit_choices_to={'recipe_version.recipe': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recepty.recipe')}, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recepty.recipeinstance'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='taste',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, help_text='Viac je lepšie', max_length=1, null=True, verbose_name='Chuť'),
        ),
    ]
