# Generated by Django 4.1 on 2022-09-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0022_alter_rating_recipe_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='recipe',
        ),
    ]
