# Generated by Django 4.1 on 2022-09-07 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0024_alter_rating_recipe_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recepty.recipe'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='recipe_instance',
            field=models.ForeignKey(blank=True, limit_choices_to={'recipe_version.recipe': models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recepty.recipe')}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recepty.recipeinstance'),
        ),
    ]
