# Generated by Django 4.1 on 2022-09-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_food_attr_userprofile_food_preferences'),
        ('recepty', '0027_remove_rating_recipe_alter_rating_recipe_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='attributes',
            field=models.ManyToManyField(to='home.food_attr'),
        ),
    ]
