# Generated by Django 4.1 on 2022-09-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alergen_alter_userprofile_food_preferences_and_more'),
        ('recepty', '0028_recipe_attributes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alergen',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='alergens',
            field=models.ManyToManyField(blank=True, help_text='Zvolte všetky alergény:', related_name='Ingredients', to='home.alergen', verbose_name='Alergény'),
        ),
    ]
