version: "3.4"

services:
  db:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  back-end:
    image: mandalinka-back-end
    build:
      context: ./back-end
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back-end:/usr/src/mandalinka/back-end
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/mandalinka/web/secrets/storage_credentials.json
    depends_on:
      - db
  front-end-web:
    image: mandalinka-front-end-web
    build:
      context: ./front-end-web
      dockerfile: ./Dockerfile
    volumes:
      - ./front-end-web:/usr/src/mandalinka/front-end-web
    ports:
      - "3000:3000"
    depends_on:
      - back-end
    links:
      - back-end:mandalinka.api.com
