# Generated by Django 4.1 on 2023-02-02 21:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import management.models.recipe_designs


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('date', models.DateField(unique=True, verbose_name='Dátum')),
                ('_public', models.BooleanField(default=False, editable=False, help_text='Označuje, či je recept verejný.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RDError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RecipeDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], default='inactive', editable=False, max_length=8)),
                ('status_changed', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Zmena statusu')),
                ('name', models.CharField(max_length=63, verbose_name='Názov')),
                ('description', models.TextField(help_text='Zadajte stručný opis jedla', max_length=127, verbose_name='Opis jedla')),
                ('thumbnail', models.ImageField(blank=True, help_text='Pridajte thumbnail', null=True, upload_to=management.models.recipe_designs.RecipeDesign.thumbnail_upload_to)),
                ('exclusive_inheritance', models.BooleanField(default=True, help_text='Predchodca bude deaktivovaný až v momente, keď tento recept aktivujete.             Toto je vysoko odporúčané, nakoľko hrozia duplicitné recepty v prípade nezaškrtnutia.', verbose_name='Deaktivovať predchodcu?')),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Profesional')], help_text='Zadajte náročnosť', verbose_name='Náročnosť')),
                ('cooking_time', models.IntegerField(help_text='Zadajte dĺžku varenia od začiatku do hotového jedla v minútach', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(900)], verbose_name='Čas varenia')),
                ('active_cooking_time', models.IntegerField(help_text='Zadajte čas, ktorý je potrebné venovať sa vareniu', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(300)], verbose_name='Aktívny čas varenia')),
                ('description_finished', models.BooleanField(default=False, help_text='Odznačte, ak ešte treba opis jedla prerobiť/opraviť/skontrolovať', verbose_name='Opis finálne hotový')),
                ('steps_finished', models.BooleanField(default=False, help_text='Odznačte, ak ešte treba postup prerobiť/opraviť', verbose_name='Postup finálne hotový')),
                ('ingredients_finished', models.BooleanField(default=False, help_text='Odznačte, ak ešte treba ingrediencie prerobiť/opraviť', verbose_name='Ingrediencie finálne hotové')),
                ('todo', models.TextField(blank=True, help_text='Sem napíš všetko, čo ešte pre tento recept nie je hotové. Veci oddeluj enterom.', verbose_name='ToDo poznámka')),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='Predajná cena')),
                ('_automatic_errors', models.ManyToManyField(blank=True, related_name='recipes', to='management.rderror', verbose_name='Chyby')),
                ('attributes', models.ManyToManyField(blank=True, help_text='Zadajte všetky atribúty jedla', related_name='recipes', to='management.attribute', verbose_name='Attribúty')),
                ('created_by', models.ForeignKey(help_text='Zvolte seba', on_delete=django.db.models.deletion.PROTECT, related_name='created_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('diet', models.ManyToManyField(blank=True, help_text='Spadá tento recept do nejakých diet?', related_name='recipes', to='management.diet', verbose_name='Dieta')),
                ('predecessor', models.ForeignKey(blank=True, help_text='V prípade, že je tento recept iba pozmenený predchádzajúci, zvolte ktorý mu predchádzal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='management.recipedesign', verbose_name='Predchodca')),
                ('required_accessories', models.ManyToManyField(blank=True, help_text='Zadajte všetky potrebné kuchynské pomôcky', related_name='recipes', to='management.kitchenaccesory', verbose_name='Potrebné kuchynské náradie')),
            ],
            options={
                'ordering': ['-status_changed', '-created'],
                'permissions': [('change_recipe_status', 'Can change recipe status')],
            },
        ),
        migrations.CreateModel(
            name='RecipeInMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('cost', models.FloatField(blank=True, default=None, null=True, verbose_name='Reálne náklady')),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='Predajná cena')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='management.menu')),
                ('recipe_design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='management.recipedesign')),
            ],
            options={
                'unique_together': {('recipe_design', 'menu')},
            },
        ),
        migrations.CreateModel(
            name='RDStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Poradie kroku')),
                ('text', models.TextField(verbose_name='Text')),
                ('thumbnail', models.ImageField(blank=True, help_text='Pridajte thumbnail', null=True, upload_to=management.models.recipe_designs.RDStep.upload_to)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='management.recipedesign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RDIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('amount', models.FloatField(help_text='Zadajte množstvo danej potraviny na dve porcie', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Množstvo')),
                ('alternative_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='management.rdingredient')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_designs', to='management.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='management.recipedesign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RMIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('amount', models.FloatField(help_text='Zadajte množstvo danej potraviny na dve porcie', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Množstvo')),
                ('alternative_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='management.rmingredient')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_designs', to='management.ingredientversion')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='management.recipeinmenu')),
            ],
            options={
                'abstract': False,
                'unique_together': {('ingredient', 'recipe')},
            },
        ),
        migrations.AddConstraint(
            model_name='recipedesign',
            constraint=models.CheckConstraint(check=models.Q(('cooking_time__gte', models.F('active_cooking_time'))), name='cooking_time_gte_active_cooking_time', violation_error_message='Čas varenia musí byť väčší alebo rovný aktívnemu času varenia'),
        ),
        migrations.AlterUniqueTogether(
            name='rdingredient',
            unique_together={('ingredient', 'recipe')},
        ),
    ]
