# Generated by Django 4.1 on 2023-02-02 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('management', '0002_menu_rderror_recipedesign_recipeinmenu_rdstep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientStockChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('amount', models.FloatField(help_text='Kladné číslo znamená pridanie, záporné odobranie', verbose_name='Množstvo')),
                ('ingredient_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_changes', to='management.ingredientversion')),
                ('unit', models.ForeignKey(blank=True, help_text='Zadajte jednotku', on_delete=django.db.models.deletion.PROTECT, to='utils.unit', verbose_name='Jednotka')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
