# Generated by Django 4.1 on 2023-01-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='property',
            field=models.CharField(choices=[('LENGTH', 'LENGTH'), ('MASS', 'MASS'), ('VOLUME', 'VOLUME'), ('NUMBER', 'NUMBER')], default='MASS', max_length=8),
        ),
    ]
