# Generated by Django 4.1 on 2023-01-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('date', models.DateField(unique=True, verbose_name='Dátum')),
                ('public', models.BooleanField(default=False, editable=False, help_text='Označuje, či je recept verejný. Nikde nemeniť manuálne, iba pomocou save(public=True)')),
            ],
        ),
    ]
