# Generated by Django 4.1 on 2022-11-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryday',
            name='recipes',
            field=models.ManyToManyField(blank=True, help_text='Zvolte, ktoré recepty budú v daný deň na výber', related_name='delivery_days', through='recipes.RecipeDeliveryInstance', to='recipes.recipe', verbose_name='Recepty'),
        ),
    ]
