# Generated by Django 4.1 on 2022-11-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryday',
            name='public',
            field=models.BooleanField(default=False, editable=False, help_text='Označuje, či je recept verejný. Nikde nemeniť manuálne, iba pomocou save(public=True)', verbose_name='Verejný'),
        ),
    ]
