# Generated by Django 4.1 on 2022-11-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_deliveryday_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryday',
            old_name='public',
            new_name='_public',
        ),
    ]
