# Generated by Django 4.1 on 2022-11-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_rename_public_deliveryday__public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryday',
            name='_public',
            field=models.BooleanField(default=False, editable=False, help_text='Označuje, či je recept verejný. Nikde nemeniť manuálne, iba pomocou save(public=True)'),
        ),
    ]
