# Generated by Django 4.1 on 2023-01-24 17:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ingredients.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0002_alter_unit_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergen',
            fields=[
                ('name', models.CharField(max_length=63, unique=True, verbose_name='Alergén')),
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Kód')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('name', models.CharField(help_text='Názov ingrediencie', max_length=31, unique=True, verbose_name='Názov')),
                ('img', models.ImageField(blank=True, default=None, help_text='Pridajte obrazok ku ingrediencií', null=True, upload_to=ingredients.models.Ingredient.img_upload_to, verbose_name='Obrázok')),
                ('alergens', models.ManyToManyField(blank=True, default=None, help_text='Zvolte všetky alergény', related_name='ingredients', to='ingredients.alergen', verbose_name='Alergény')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='utils.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], default='inactive', editable=False, max_length=8)),
                ('status_changed', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Zmena statusu')),
                ('_temporary_amount', models.FloatField(help_text='Zadajte množstvo', verbose_name='Množstvo')),
                ('cost', models.FloatField(help_text='Zadajte cenu na zvolené množstvo zvolenej jednotky', verbose_name='Cena na jednotku')),
                ('source', models.CharField(help_text='Toto ešte bude raz foreign key na dodávatela', max_length=64)),
                ('_temporary_unit', models.ForeignKey(help_text='Zadajte jednotku', on_delete=django.db.models.deletion.PROTECT, to='utils.unit', verbose_name='Jednotka')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='versions', to='ingredients.ingredient')),
            ],
            options={
                'ordering': ('created',),
                'permissions': [('change_ingredient_status', 'Can change ingredient status')],
            },
        ),
    ]
