# Generated by Django 4.1 on 2023-01-22 14:46

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientversion',
            options={'ordering': ('created',), 'permissions': [('change_ingredient_status', 'Can change ingredient status')]},
        ),
        UnaccentExtension(),
    ]
