# Generated by Django 4.1 on 2023-01-24 18:00

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        UnaccentExtension(),
    ]
