# Generated by Django 4.1 on 2022-10-20 20:34

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=20)),
                ('newsletter', models.BooleanField(default=False)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('is_email_valid', models.BooleanField(default=False)),
                ('is_address_valid', models.BooleanField(default=False)),
                ('is_payment_valid', models.BooleanField(default=False)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('default_num_portions', models.IntegerField(default=2)),
                ('pescetarian', models.BooleanField(default=False, verbose_name='Pescetarian')),
                ('vegetarian', models.BooleanField(default=False, verbose_name='Vegetarian')),
                ('vegan', models.BooleanField(default=False, verbose_name='Vegan')),
                ('gluten_free', models.BooleanField(default=False, verbose_name='Gluten Free')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Adresa a číslo domu')),
                ('address_note', models.TextField(blank=True, help_text='(zvonček, poschodie, ...)', max_length=256, verbose_name='Poznámka pre kuriéra')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Mesto')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='Okres')),
                ('postal', models.CharField(blank=True, max_length=6, verbose_name='PSČ')),
                ('country', models.CharField(blank=True, max_length=32, verbose_name='Krajina')),
                ('coordinates', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.BooleanField(default=False)),
            ],
        ),
    ]
