# Generated by Django 4.1 on 2022-09-15 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergen',
            fields=[
                ('title', models.CharField(max_length=63, verbose_name='Alergén')),
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Kód alergénu')),
            ],
        ),
        migrations.CreateModel(
            name='CityDistrictPostal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=150)),
                ('postal', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FoodAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('num_portions', models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6')], default=2)),
                ('street', models.CharField(blank=True, max_length=150)),
                ('house_no', models.CharField(max_length=8)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('postal', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=2)),
                ('newsletter', models.BooleanField(default=False)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('alergies', models.ManyToManyField(blank=True, related_name='users', to='home.alergen')),
                ('food_preferences', models.ManyToManyField(blank=True, related_name='users', to='home.foodattribute')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
