# Generated by Django 4.1 on 2022-09-19 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepty', '0007_alter_recipeinstance_amount_and_more'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_instance', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='recepty.deliveryinstance')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecipeOrderInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions', models.IntegerField(verbose_name='Množstvo porcií')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.order')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepty.recipeinstance')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='recipes',
            field=models.ManyToManyField(related_name='orders', through='home.RecipeOrderInstance', to='recepty.recipeinstance'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
