# Generated by Django 4.1 on 2022-10-20 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0014_alter_user_email'),
        ('recepty', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='recepty.deliveryday'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipes',
            field=models.ManyToManyField(blank=True, help_text='Zvolte si recepty a množstvo porcií', related_name='orders', through='recepty.RecipeOrderInstance', to='recepty.recipeversion', verbose_name='Recepty'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='alergies',
            field=models.ManyToManyField(blank=True, related_name='users', to='recepty.alergen'),
        ),
        migrations.AddField(
            model_name='user',
            name='food_preferences',
            field=models.ManyToManyField(blank=True, related_name='users', to='recepty.foodattribute'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
