# Generated by Django 4.1 on 2022-10-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pronoun',
            field=models.CharField(choices=[('male', 'Mužský rod'), ('female', 'Ženský rod'), ('they', 'Vykanie')], default='they', max_length=16, verbose_name='Oslovovanie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Meno'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Priezvisko'),
        ),
        migrations.AlterField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+421', help_text='Môže byť použité počas doručovania', max_length=20, verbose_name='Telefónne číslo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_conditions',
            field=models.BooleanField(),
        ),
    ]
