# Generated by Django 4.1 on 2022-09-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile_newsletter_userprofile_terms_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_attr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food_preferences',
            field=models.ManyToManyField(to='home.food_attr'),
        ),
    ]
