# Generated by Django 4.1 on 2022-09-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order_alter_userprofile_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeorderinstance',
            name='order',
        ),
        migrations.RemoveField(
            model_name='recipeorderinstance',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_instance',
        ),
    ]
