# Generated by Django 4.1 on 2022-10-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_pronoun_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Domov', help_text='Názov, pod ktorým uložíme túto adresu', max_length=32, verbose_name='Názov adresy')),
                ('street_num', models.CharField(help_text='Nezabudnite pridať číslo domu', max_length=128, verbose_name='Adresa a číslo domu')),
                ('note', models.TextField(blank=True, help_text='(zvonček, poschodie, ...)', max_length=256, verbose_name='Poznámka pre kuriéra')),
                ('city', models.CharField(max_length=100, verbose_name='Mesto')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='Okres')),
                ('postal', models.CharField(max_length=6, verbose_name='PSČ')),
                ('country', models.CharField(blank=True, max_length=32, verbose_name='Krajina')),
                ('coordinates', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_note',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_address_valid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal',
        ),
        migrations.AlterField(
            model_name='user',
            name='pronoun',
            field=models.CharField(choices=[('male', 'Mužský rod'), ('female', 'Ženský rod'), ('they', 'Vykanie')], max_length=16, verbose_name='Oslovovanie'),
        ),
        migrations.AddField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(related_name='users', to='home.address'),
        ),
    ]
