# Generated by Django 4.1 on 2022-09-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0028_recipe_attributes'),
        ('home', '0003_food_attr_userprofile_food_preferences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food_attr',
            new_name='FoodAttribute',
        ),
    ]
