# Generated by Django 4.1 on 2022-09-19 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_recipeorderinstance_order_and_more'),
        ('recepty', '0008_deliveryday_recipeorderinstance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='recepty.deliveryday'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipes',
            field=models.ManyToManyField(help_text='Zvolte si recepty a množstvo porcií', related_name='orders', through='recepty.RecipeOrderInstance', to='recepty.recipeversion', verbose_name='Recepty'),
        ),
        migrations.DeleteModel(
            name='RecipeOrderInstance',
        ),
    ]
