# Generated by Django 4.1 on 2022-10-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_address_remove_user_address_remove_user_address_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
