# Generated by Django 4.1 on 2022-10-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0012_alter_recipeorderinstance_amount_and_more'),
        ('home', '0005_alter_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recipes',
            field=models.ManyToManyField(blank=True, help_text='Zvolte si recepty a množstvo porcií', related_name='orders', through='recepty.RecipeOrderInstance', to='recepty.recipeversion', verbose_name='Recepty'),
        ),
    ]
