# Generated by Django 4.1 on 2022-10-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_address_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='users', to='home.address'),
        ),
    ]
