# Generated by Django 4.1 on 2022-09-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alergen_alter_userprofile_food_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='num_portions',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6')], default=2),
        ),
    ]
