# Generated by Django 4.1 on 2022-10-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_order_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gluten_free',
            field=models.BooleanField(default=False, verbose_name='Gluten Free'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pescetarian',
            field=models.BooleanField(default=False, verbose_name='Pescetarian'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vegan',
            field=models.BooleanField(default=False, verbose_name='Vegan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vegetarian',
            field=models.BooleanField(default=False, verbose_name='Vegetarian'),
        ),
    ]
