# Generated by Django 4.1 on 2022-10-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_street_num_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='coordinates',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
