# Generated by Django 4.1 on 2022-10-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userprofile_gluten_free_userprofile_pescetarian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.BooleanField(default=False),
        ),
    ]
