# Generated by Django 4.1 on 2022-10-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_order_pickup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='street',
            new_name='address',
        ),
    ]
