# Generated by Django 4.1 on 2022-10-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_street_userprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='house_no',
        ),
    ]
