# Generated by Django 4.1 on 2022-10-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_user_addresses_address_primary_address_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='gluten_free',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pescetarian',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vegan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vegetarian',
        ),
        migrations.AddField(
            model_name='user',
            name='diets',
            field=models.ManyToManyField(related_name='users', to='home.diet'),
        ),
    ]
