# Generated by Django 4.1 on 2022-10-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_diet_remove_user_gluten_free_remove_user_pescetarian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_num_portions',
            field=models.IntegerField(choices=[(2, 2), (4, 4), (6, 6)], default=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='diets',
            field=models.ManyToManyField(blank=True, related_name='users', to='home.diet'),
        ),
    ]
