# Generated by Django 4.1 on 2022-10-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userprofile_address_note_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=150, verbose_name='Adresa a číslo domu'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mesto'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('SK', 'Slovensko'), ('00', 'Iné')], max_length=32, verbose_name='Krajina'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=50, verbose_name='Okres'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal',
            field=models.CharField(blank=True, max_length=6, verbose_name='PSČ'),
        ),
    ]
