# Generated by Django 4.1 on 2022-10-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_userprofile_address_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('00', 'Iné'), ('SK', 'Slovensko')], max_length=32, verbose_name='Krajina'),
        ),
    ]
