# Generated by Django 4.1 on 2022-11-05 13:13

import customers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.BooleanField(default=False, help_text='True - pickup, False - delivery')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeOrderInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions', models.IntegerField(validators=[customers.models.validate_portions], verbose_name='Množstvo porcií')),
                ('amount_rating', models.CharField(blank=True, choices=[(None, 'Vyhovovala vám porcia'), ('1', 'Porcia bola malá'), ('2', 'Porcia mohla byť trochu väčšia'), ('3', 'Porcia bola akurát'), ('4', 'Stačilo by trochu menej'), ('5', 'Porcia bola príliš veľká')], default=None, help_text='Sedelo množstvo jedla s objednanou porciou?', max_length=1, null=True, verbose_name='Hodnotenie množstva')),
                ('taste_rating', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, help_text='Viac je lepšie', max_length=1, null=True, verbose_name='Chuť')),
                ('delivery_rating', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, help_text='Viac je lepšie', max_length=1, null=True, verbose_name='Doručenie')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_mid', to='customers.order')),
            ],
        ),
    ]
