# Generated by Django 4.1 on 2022-11-05 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0001_initial'),
        ('recipes', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeorderinstance',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='deliveries.deliveryday'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='orders', through='customers.RecipeOrderInstance', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
