# Generated by Django 4.1 on 2022-11-05 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0002_initial'),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeorderinstance',
            name='delivery_rating',
            field=models.CharField(blank=True, choices=[(None, 'Zadajte hodnotenie'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, help_text='Viac je lepšie', max_length=1, null=True, verbose_name='Doručenie'),
        ),
        migrations.AlterField(
            model_name='recipeorderinstance',
            name='taste_rating',
            field=models.CharField(blank=True, choices=[(None, 'Zadajte hodnotenie'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, help_text='Viac je lepšie', max_length=1, null=True, verbose_name='Chuť'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('user', 'delivery_day')},
        ),
    ]
