# Generated by Django 4.1 on 2022-10-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergen',
            fields=[
                ('title', models.CharField(max_length=63, verbose_name='Alergén')),
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Kód alergénu')),
            ],
        ),
    ]
