# Generated by Django 4.1 on 2022-11-05 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergen',
            fields=[
                ('name', models.CharField(max_length=63, unique=True, verbose_name='Alergén')),
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Kód')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Atribút')),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Názov ingrediencie', max_length=31, unique=True, verbose_name='Názov')),
                ('img', models.ImageField(blank=True, default=None, help_text='Pridajte obrazok ku kroku', null=True, upload_to='ingredients', verbose_name='Obrázok')),
                ('unit', models.CharField(choices=[(None, 'Zvolte jednotku'), ('g', 'gramy'), ('ml', 'mililitre'), ('ks', 'kusy')], help_text='Zvolte jednotku', max_length=3, verbose_name='Jednotka')),
                ('price_per_unit', models.FloatField(help_text='Zadajte cenu na nižšie zvolenú jednotku', verbose_name='Cena na jednotku')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Čas vzniku')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Naposledy upravené')),
                ('alergens', models.ManyToManyField(blank=True, help_text='Zvolte všetky alergény:', related_name='ingredients', to='recipes.alergen', verbose_name='Alergény')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Zadajte množstvo danej potraviny', verbose_name='Množstvo')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True, verbose_name='Názov')),
                ('description', models.TextField(help_text='Zadajte stručný opis jedla', max_length=127, verbose_name='Opis jedla')),
                ('thumbnail', models.ImageField(blank=True, help_text='Pridajte thumbnail', null=True, upload_to='recipes')),
                ('active', models.BooleanField(blank=True, help_text='Používa sa tento recept ešte?', verbose_name='Aktívny')),
                ('steps', models.TextField(blank=True, help_text='Jednotlivé kroky oddelujte enterom', max_length=1024, verbose_name='Postup')),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Profesional')], help_text='Zadajte náročnosť', verbose_name='Náročnosť')),
                ('StF_time', models.IntegerField(help_text='Zadajte dĺžku varenia od začiatku do hotového jedla', validators=[recipes.models.validate_cooking_time_range], verbose_name='Čas varenia')),
                ('active_time', models.IntegerField(help_text='Zadajte dĺžku aktívneho času varenia', validators=[recipes.models.validate_cooking_time_range], verbose_name='Čas prípravy')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Čas vzniku')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Naposledy upravené')),
                ('attributes', models.ManyToManyField(blank=True, help_text='Zadajte všetky atribúty jedla', related_name='recipes', to='recipes.attribute', verbose_name='Attribúty')),
                ('created_by', models.ForeignKey(help_text='Zvolte seba', on_delete=django.db.models.deletion.PROTECT, related_name='created_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('diet', models.ManyToManyField(blank=True, help_text='Spadá tento recept do nejakých diet?', related_name='recipes', to='recipes.diet', verbose_name='Dieta')),
                ('ingredients', models.ManyToManyField(help_text='Zvolte všetky ingrediencie', related_name='recipes', through='recipes.IngredientInstance', to='recipes.ingredient', verbose_name='Ingrediencie')),
                ('predecessor', models.ForeignKey(blank=True, help_text='V prípade, že je tento recept iba pozmenený predchádzajúci, zvolte ktorý mu predchádzal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='recipes.recipe', verbose_name='Predchodca')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDeliveryInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(verbose_name='Reálne náklady')),
                ('price', models.FloatField(verbose_name='Predajná cena')),
                ('delivery_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes_mid', to='deliveries.deliveryday')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_days_mid', to='recipes.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientinstance',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients_mid', to='recipes.recipe'),
        ),
    ]
