# Generated by Django 4.1 on 2023-01-30 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import recipes.models
import utils.validators
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('ingredients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Pridajte ikonku', null=True, upload_to=recipes.models.Attribute.icon_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Pridajte ikonku', null=True, upload_to=recipes.models.Diet.icon_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='KitchenAccesory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Pridajte ikonku', null=True, upload_to=recipes.models.KitchenAccesory.icon_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDeliveryInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(blank=True, default=None, null=True, verbose_name='Reálne náklady')),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='Predajná cena')),
                ('delivery_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='deliveries.deliveryday')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], default='inactive', editable=False, max_length=8)),
                ('status_changed', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Zmena statusu')),
                ('name', models.CharField(max_length=63, verbose_name='Názov')),
                ('description', models.TextField(help_text='Zadajte stručný opis jedla', max_length=127, verbose_name='Opis jedla')),
                ('thumbnail', models.ImageField(blank=True, help_text='Pridajte thumbnail', null=True, upload_to=recipes.models.RecipeDesign.thumbnail_upload_to)),
                ('exclusive_inheritance', models.BooleanField(default=True, help_text='Predchodca bude deaktivovaný až v momente, keď tento recept aktivujete.             Toto je vysoko odporúčané, nakoľko hrozia duplicitné recepty v prípade nezaškrtnutia.', verbose_name='Deaktivovať predchodcu?')),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Profesional')], help_text='Zadajte náročnosť', verbose_name='Náročnosť')),
                ('cooking_time', models.IntegerField(help_text='Zadajte dĺžku varenia od začiatku do hotového jedla v minútach', validators=[recipes.models.validate_cooking_time_range], verbose_name='Čas varenia')),
                ('active_cooking_time', models.IntegerField(help_text='Zadajte čas, ktorý je potrebné venovať sa vareniu', validators=[recipes.models.validate_cooking_time_range], verbose_name='Aktívny čas varenia')),
                ('description_finished', models.BooleanField(default=False, help_text='Odznačte, ak ešte treba opis jedla prerobiť/opraviť/skontrolovať', verbose_name='Opis finálne hotový')),
                ('steps_finished', models.BooleanField(default=False, help_text='Odznačte, ak ešte treba postup prerobiť/opraviť', verbose_name='Postup finálne hotový')),
                ('ingredients_finished', models.BooleanField(default=False, help_text='Odznačte, ak ešte treba ingrediencie prerobiť/opraviť', verbose_name='Ingrediencie finálne hotové')),
                ('todo', models.TextField(blank=True, help_text='Sem napíš všetko, čo ešte pre tento recept nie je hotové. Veci oddeluj enterom.', verbose_name='ToDo poznámka')),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='Predajná cena')),
            ],
            options={
                'ordering': ['-status_changed', '-created'],
                'permissions': [('change_recipe_status', 'Can change recipe status')],
            },
        ),
        migrations.CreateModel(
            name='RecipeDesignError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('number', models.IntegerField(validators=[utils.validators.validate_positivity], verbose_name='Poradie kroku')),
                ('text', models.TextField(verbose_name='Text')),
                ('thumbnail', models.ImageField(blank=True, help_text='Pridajte thumbnail', null=True, upload_to=recipes.models.Step.upload_to)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipedesign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='ingredients.ingredientversion')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipedeliveryinstance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recipedesign',
            name='_automatic_errors',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.recipedesignerror', verbose_name='Chyby'),
        ),
        migrations.AddField(
            model_name='recipedesign',
            name='attributes',
            field=models.ManyToManyField(blank=True, help_text='Zadajte všetky atribúty jedla', related_name='recipes', to='recipes.attribute', verbose_name='Attribúty'),
        ),
        migrations.AddField(
            model_name='recipedesign',
            name='created_by',
            field=models.ForeignKey(help_text='Zvolte seba', on_delete=django.db.models.deletion.PROTECT, related_name='created_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='recipedesign',
            name='diet',
            field=models.ManyToManyField(blank=True, help_text='Spadá tento recept do nejakých diet?', related_name='recipes', to='recipes.diet', verbose_name='Dieta'),
        ),
        migrations.AddField(
            model_name='recipedesign',
            name='predecessor',
            field=models.ForeignKey(blank=True, help_text='V prípade, že je tento recept iba pozmenený predchádzajúci, zvolte ktorý mu predchádzal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='recipes.recipedesign', verbose_name='Predchodca'),
        ),
        migrations.AddField(
            model_name='recipedesign',
            name='required_accessories',
            field=models.ManyToManyField(blank=True, help_text='Zadajte všetky potrebné kuchynské pomôcky', related_name='recipes', to='recipes.kitchenaccesory', verbose_name='Potrebné kuchynské náradie'),
        ),
        migrations.AddField(
            model_name='recipedeliveryinstance',
            name='recipe_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_days', to='recipes.recipedesign'),
        ),
        migrations.CreateModel(
            name='RecipeDesignIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('amount', models.FloatField(help_text='Zadajte množstvo danej potraviny na dve porcie', validators=[utils.validators.validate_positivity], verbose_name='Množstvo')),
                ('alternative_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='recipes.recipedesigningredient')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_designs', to='ingredients.ingredient')),
                ('recipe_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipedesign')),
            ],
            options={
                'unique_together': {('ingredient', 'recipe_design')},
            },
        ),
        migrations.AddConstraint(
            model_name='recipedesign',
            constraint=models.CheckConstraint(check=models.Q(('cooking_time__gte', models.F('active_cooking_time'))), name='cooking_time_gte_active_cooking_time', violation_error_message='Čas varenia musí byť väčší alebo rovný aktívnemu času varenia'),
        ),
        migrations.AlterUniqueTogether(
            name='recipedeliveryinstance',
            unique_together={('recipe_design', 'delivery_day')},
        ),
        UnaccentExtension(),
    ]
