# Generated by Django 4.1 on 2022-10-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Atribút')),
            ],
        ),
        migrations.RenameField(
            model_name='alergen',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='alergen',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Kód'),
        ),
    ]
