# Generated by Django 4.1 on 2022-11-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='active',
            new_name='is_active',
        ),
    ]
