# Generated by Django 4.1 on 2022-10-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_attribute_rename_title_alergen_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Názov ingrediencie', max_length=31, unique=True, verbose_name='Názov')),
                ('price_per_unit', models.FloatField(help_text='Zadajte cenu na nižšie zvolenú jednotku', verbose_name='Cena na jednotku')),
                ('img', models.ImageField(blank=True, default=None, help_text='Pridajte obrazok ku kroku', null=True, upload_to='ingredients', verbose_name='Obrázok')),
                ('unit', models.CharField(choices=[(None, 'Zvolte jednotku'), ('g', 'gramy'), ('ml', 'mililitre'), ('ks', 'kusy')], help_text='Zvolte jednotku', max_length=3, verbose_name='Jednotka')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Čas vzniku')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Naposledy upravené')),
                ('alergens', models.ManyToManyField(blank=True, help_text='Zvolte všetky alergény:', related_name='ingredients', to='recipes.alergen', verbose_name='Alergény')),
            ],
        ),
    ]
