# Generated by Django 4.1 on 2022-10-25 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_remove_user_diets_user_diet'),
        ('recipes', '0003_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Zadajte množstvo danej potraviny', verbose_name='Množstvo')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, unique=True, verbose_name='Názov')),
                ('description', models.TextField(help_text='Zadajte stručný opis jedla', max_length=127, verbose_name='Opis jedla')),
                ('thumbnail', models.ImageField(blank=True, help_text='Pridajte thumbnail', null=True, upload_to='recipes')),
                ('active', models.BooleanField(blank=True, verbose_name='Aktívny')),
                ('steps', models.TextField(blank=True, help_text='Jednotlivé kroky oddelujte enterom', max_length=1024, verbose_name='Postup')),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Profesional')], help_text='Zadajte náročnosť', verbose_name='Náročnosť')),
                ('StF_time', models.IntegerField(help_text='Zadajte dĺžku varenia od začiatku do hotového jedla', validators=[recipes.models.validate_cooking_time_range], verbose_name='Čas varenia')),
                ('active_time', models.IntegerField(help_text='Zadajte dĺžku aktívneho času varenia', validators=[recipes.models.validate_cooking_time_range], verbose_name='Čas prípravy')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Čas vzniku')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Naposledy upravené')),
                ('attributes', models.ManyToManyField(blank=True, null=True, related_name='recipes', to='recipes.attribute')),
                ('created_by', models.ForeignKey(blank=True, help_text='Zvolte seba', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('diet', models.ManyToManyField(related_name='recipes', to='accounts.diet')),
                ('ingredients', models.ManyToManyField(help_text='Zvolte všetky ingrediencie', related_name='recipes', through='recipes.IngredientInstance', to='recipes.ingredient', verbose_name='Ingrediencie')),
                ('predecessor', models.ForeignKey(blank=True, help_text='V prípade, že je tento recept iba pozmenený predchádzajúci, zvolte ktorý mu predchádzal', on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='recipes.recipe', verbose_name='predchodca')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientinstance',
            name='recipe_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.recipe'),
        ),
    ]
