# Generated by Django 4.1 on 2022-11-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipedeliveryinstance_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedeliveryinstance',
            name='cost',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Reálne náklady'),
        ),
        migrations.AlterField(
            model_name='recipedeliveryinstance',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Predajná cena'),
        ),
    ]
