# Generated by Django 4.1 on 2022-11-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipedeliveryinstance_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'permissions': [('toggle_recipe_is_active', 'Can activate or deactivate any recipe')]},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Používa sa tento recept ešte?', verbose_name='Aktívny'),
        ),
    ]
