# Generated by Django 4.1 on 2022-10-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Patrí toto jedlo do nejakej diety')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=models.ManyToManyField(related_name='recipes', to='recipes.diet'),
        ),
    ]
