# Generated by Django 4.1 on 2022-11-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_options_alter_recipe_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_active',
            field=models.BooleanField(default=False, editable=False, help_text='Používa sa táto ingrediencia ešte?', verbose_name='Aktívny'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=False, editable=False, help_text='Používa sa tento recept ešte?', verbose_name='Aktívny'),
        ),
    ]
