# Generated by Django 4.1 on 2022-11-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_ingredient_is_active_alter_recipe_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='is_active',
            new_name='_is_active',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='is_active',
            new_name='_is_active',
        ),
    ]
