# Generated by Django 4.1 on 2022-11-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_is_active_ingredient__is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='_is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='StF_time',
            new_name='StF_cooking_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='active_time',
            new_name='active_cooking_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='_is_active',
            new_name='is_active',
        ),
    ]
