# Generated by Django 4.1 on 2022-11-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_rename__is_active_ingredient_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'permissions': [('toggle_is_active', 'Can activate or deactivate any recipe')]},
        ),
    ]
