# Generated by Django 4.1 on 2022-11-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='exclusive_predecessor',
            field=models.BooleanField(default=True, help_text='Predchodca bude deaktivovaný až v momente, keď tento recept aktivujete', verbose_name='Deaktivovať predchodcu?'),
        ),
    ]
