# Generated by Django 4.1 on 2022-11-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_exclusive_predecessor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'permissions': [('toggle_recipe_is_active', 'Can activate or deactivate any recipe')]},
        ),
    ]
