# Generated by Django 4.1 on 2022-11-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'permissions': [('toggle_is_active_ingredient', 'Can activate or deactivate any ingredient')]},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'permissions': [('toggle_is_active_recipe', 'Can activate or deactivate any recipe')]},
        ),
    ]
