# Generated by Django 4.1 on 2022-12-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_ingredient_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='exclusive_predecessor',
            field=models.BooleanField(default=True, help_text='Predchodca bude deaktivovaný až v momente, keď tento recept aktivujete.             Toto je vysoko odporúčané, nakoľko hrozia duplicitné recepty v prípade nezaškrtnutia.', verbose_name='Deaktivovať predchodcu?'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=63, verbose_name='Názov'),
        ),
    ]
