# Generated by Django 4.1 on 2023-01-02 12:01

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_recipe_exclusive_predecessor_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='alergens',
            field=models.ManyToManyField(blank=True, default=None, help_text='Zvolte všetky alergény', related_name='ingredients', to='recipes.alergen', verbose_name='Alergény'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='StF_cooking_time',
            field=models.IntegerField(help_text='Zadajte dĺžku varenia od začiatku do hotového jedla v minútach', validators=[recipes.models.validate_cooking_time_range], verbose_name='Čas varenia'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='active_cooking_time',
            field=models.IntegerField(help_text='Zadajte dĺžku aktívneho času varenia v minútach', validators=[recipes.models.validate_cooking_time_range], verbose_name='Čas prípravy'),
        ),
    ]
