# Generated by Django 4.1 on 2023-01-03 14:48

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_alter_ingredient_alergens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinstance',
            name='amount',
            field=models.IntegerField(help_text='Zadajte množstvo danej potraviny', validators=[recipes.models.validate_positivity], verbose_name='Množstvo'),
        ),
    ]
