# Generated by Django 4.1 on 2023-01-03 15:36

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_alter_ingredientinstance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinstance',
            name='amount',
            field=models.IntegerField(help_text='Zadajte množstvo danej potraviny na dve porcie', validators=[recipes.models.validate_positivity], verbose_name='Množstvo'),
        ),
    ]
