# Generated by Django 4.1 on 2023-01-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_recipe_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='errors',
            field=models.CharField(default='', help_text='String of IDs representing statuses separated by commas', max_length=10, verbose_name='Status'),
        ),
    ]
