# Generated by Django 4.1 on 2023-01-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_recipe_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='steps_finished',
            field=models.BooleanField(default=False, verbose_name='Kroky finalizované'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='errors',
            field=models.CharField(default='', help_text='String of IDs representing errors separated by commas 0: Missing thumbnail | 1: Missing steps | 2: Missing ingredients | 3: Missing attributes | 4: Missing diet | 11: Unfinished steps | 12: Unfinished ingredients | 13: Unfinished attributes | 14: Unfinished diet', max_length=10, verbose_name='Errors'),
        ),
    ]
