# Generated by Django 4.1 on 2023-01-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_recipe_steps_finished_alter_recipe_errors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='errors',
        ),
        migrations.AddField(
            model_name='recipe',
            name='automatic_errors',
            field=models.CharField(default='', help_text='String of IDs representing errors separated by commas 0: Missing thumbnail | 1: Missing steps | 2: Missing ingredients | 3: Missing attributes | 4: Missing diet', max_length=10, verbose_name='Errors'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps_finished',
            field=models.BooleanField(default=False, help_text='Odznačte, ak ešte treba postup prerobiť/opraviť', verbose_name='Postup finálne hotový'),
        ),
    ]
