# Generated by Django 4.1 on 2023-01-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_recipe_ingredients_finished_recipe_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description_finished',
            field=models.BooleanField(default=False, help_text='Odznačte, ak ešte treba opis jedla prerobiť/opraviť/skontrolovať', verbose_name='Opis finálne hotový'),
        ),
    ]
