# Generated by Django 4.1 on 2023-01-05 15:45

from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_recipe_description_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='steps',
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Poradie kroku')),
                ('text', models.TextField(verbose_name='Text')),
                ('thumbnail', models.ImageField(blank=True, help_text='Pridajte thumbnail', null=True, upload_to=recipes.models.Step.upload_to)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('number', 'recipe'), name='step_number_uniqueness'),
        ),
    ]
