# Generated by Django 4.1 on 2023-01-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_remove_step_step_number_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinstance',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_mid', to='recipes.recipe'),
        ),
    ]
