# Generated by Django 4.1 on 2023-01-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0030_alter_ingredientinstance_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='automatic_errors',
            field=models.CharField(default='', help_text='String of IDs representing errors separated by commas 0: Missing thumbnail | 1: Missing steps | 2: Missing ingredients | 3: Missing attributes | 4: Missing diet | 5: ToDo list not empty', max_length=10, verbose_name='Errors'),
        ),
    ]
