# Generated by Django 4.1 on 2023-01-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0032_alter_recipe_automatic_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('Preparation', 'Preparation'), ('Active', 'Active'), ('Retired', 'Retired')], default='Preparation', max_length=20),
        ),
    ]
