# Generated by Django 4.1 on 2023-01-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0034_statuses_remove_recipe_is_active_alter_recipe_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statuses',
        ),
    ]
