# Generated by Django 4.1 on 2023-01-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0035_delete_statuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'permissions': [('toggle_recipe_status', 'Can change recipe status')]},
        ),
    ]
