# Generated by Django 4.1 on 2023-01-12 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0036_alter_recipe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='last_status_change',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 21, 54, 9, 484774), editable=False),
            preserve_default=False,
        ),
    ]
