# Generated by Django 4.1 on 2023-01-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0037_recipe_last_status_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='last_status_change',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('Preparation', 'Preparation'), ('Active', 'Active'), ('Retired', 'Retired')], default='Preparation', max_length=20),
        ),
    ]
