# Generated by Django 4.1 on 2023-01-17 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0038_alter_recipe_last_status_change_alter_recipe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='last_status_change',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 17, 12, 22, 21, 447259)),
            preserve_default=False,
        ),
    ]
