# Generated by Django 4.1 on 2023-01-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0039_alter_recipe_last_status_change'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('StF_cooking_time__gte', models.F('active_cooking_time'))), name='StF_cooking_time_gte_active_cooking_time'),
        ),
    ]
