# Generated by Django 4.1 on 2023-01-17 18:07

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0040_recipe_stf_cooking_time_gte_active_cooking_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='StF_cooking_time_gte_active_cooking_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='StF_cooking_time',
            new_name='cooking_time',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='active_cooking_time',
            field=models.IntegerField(help_text='Zadajte čas, ktorý je potrebné venovať sa vareniu', validators=[recipes.models.validate_cooking_time_range], verbose_name='Aktívny čas varenia'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('cooking_time__gte', models.F('active_cooking_time'))), name='cooking_time_gte_active_cooking_time', violation_error_message='Čas varenia musí byť väčší alebo rovný aktívnemu času varenia'),
        ),
    ]
