# Generated by Django 4.1 on 2023-01-17 18:37

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0041_remove_recipe_stf_cooking_time_gte_active_cooking_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenAccesory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Pridajte ikonku', null=True, upload_to=recipes.models.KitchenAccesory.icon_upload_to)),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='icon',
            field=models.ImageField(blank=True, help_text='Pridajte ikonku', null=True, upload_to=recipes.models.Attribute.icon_upload_to),
        ),
        migrations.AddField(
            model_name='diet',
            name='icon',
            field=models.ImageField(blank=True, help_text='Pridajte ikonku', null=True, upload_to=recipes.models.Diet.icon_upload_to),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='required_accessories',
            field=models.ManyToManyField(blank=True, help_text='Zadajte všetky potrebné kuchynské pomôcky', related_name='recipes', to='recipes.kitchenaccesory', verbose_name='Potrebné kuchynské náradie'),
        ),
    ]
