# Generated by Django 4.1 on 2023-01-17 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0042_kitchenaccesory_attribute_icon_diet_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='is_active',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='last_status_change',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 17, 19, 32, 26, 207078)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Retired', 'Retired')], default='Inactive', max_length=20),
        ),
    ]
