# Generated by Django 4.1 on 2023-01-17 19:38

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0043_remove_ingredient_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='img',
            field=models.ImageField(blank=True, default=None, help_text='Pridajte obrazok ku ingrediencií', null=True, upload_to=recipes.models.Ingredient.img_upload_to, verbose_name='Obrázok'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='status',
            field=models.CharField(choices=[('Preparation', 'Preparation'), ('Active', 'Active'), ('Retired', 'Retired')], default='Preparation', max_length=20),
        ),
    ]
