# Generated by Django 4.1 on 2023-01-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0044_alter_ingredient_img_alter_ingredient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinstance',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='recipes.ingredient'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('sign', models.CharField(max_length=6, unique=True)),
                ('conversion_rate', models.DecimalField(decimal_places=6, max_digits=6, verbose_name='Konštanta na premenu na base_unit')),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sub_units', to='recipes.unit')),
            ],
        ),
    ]
