# Generated by Django 4.1 on 2023-01-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0045_alter_ingredientinstance_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sub_units', to='recipes.unit'),
        ),
    ]
