# Generated by Django 4.1 on 2023-01-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0047_alter_unit_conversion_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=6, max_digits=13, verbose_name='Konštanta na premenu na base_unit'),
        ),
    ]
