# Generated by Django 4.1 on 2023-01-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0048_alter_unit_conversion_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='system',
            field=models.CharField(choices=[('METRIC', 'METRIC'), ('IMPERIAL', 'IMPERIAL')], default='METRIC', max_length=8),
        ),
    ]
