# Generated by Django 4.1 on 2023-01-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0049_unit_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='last_status_change',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.CreateModel(
            name='IngredientVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Preparation', 'Preparation'), ('Active', 'Active'), ('Retired', 'Retired')], default='Preparation', max_length=20)),
                ('last_status_change', models.DateTimeField(auto_now_add=True)),
                ('price_per_unit', models.FloatField(help_text='Zadajte cenu na zvolenú jednotku', verbose_name='Cena na jednotku')),
                ('source', models.CharField(help_text='Toto ešte bude raz foreign key na dodávatela', max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Čas vzniku')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Naposledy upravené')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='versions', to='recipes.ingredient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='recipes.unit')),
            ],
            options={
                'permissions': [('toggle_is_active_ingredient', 'Can activate or deactivate any ingredient')],
            },
        ),
    ]
