# Generated by Django 4.1 on 2023-01-18 14:38

from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0050_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientInRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Zadajte množstvo danej potraviny na dve porcie', validators=[recipes.models.validate_positivity], verbose_name='Množstvo')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_mid', to='recipes.ingredientversion')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, help_text='Zvolte všetky ingrediencie', related_name='recipes', through='recipes.IngredientInRecipe', to='recipes.ingredientversion', verbose_name='Ingrediencie'),
        ),
        migrations.DeleteModel(
            name='IngredientInstance',
        ),
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_mid', to='recipes.recipe'),
        ),
    ]
