# Generated by Django 4.1 on 2023-01-18 16:56

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0052_rename_price_per_unit_ingredientversion_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='price',
            field=models.FloatField(default=0, help_text=recipes.models.Recipe.cost, verbose_name='Predajná cena'),
        ),
    ]
