# Generated by Django 4.1 on 2023-01-18 17:00

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0053_recipe_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='price',
            field=models.FloatField(blank=True, default=None, help_text=recipes.models.Recipe.cost, null=True, verbose_name='Predajná cena'),
        ),
    ]
