# Generated by Django 4.1 on 2023-01-18 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0054_alter_recipe_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientversion',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='recipes.unit'),
        ),
    ]
