# Generated by Django 4.1 on 2023-01-24 17:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0055_remove_ingredientversion_unit_ingredient_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='alergens',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='ingredientversion',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='base_unit',
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-status_changed', '-created'], 'permissions': [('change_recipe_status', 'Can change recipe status')]},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='exclusive_predecessor',
            new_name='exclusive_inheritance',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='automatic_errors',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='last_status_change',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='status',
        ),
        migrations.AddField(
            model_name='recipe',
            name='_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], default='inactive', editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Vytvorené'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Upravené'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='status_changed',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Zmena statusu'),
        ),
        migrations.AddField(
            model_name='step',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Vytvorené'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Upravené'),
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_mid', to='ingredients.ingredientversion'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, help_text='Zvolte všetky ingrediencie', related_name='recipes', through='recipes.IngredientInRecipe', to='ingredients.ingredientversion', verbose_name='Ingrediencie'),
        ),
        migrations.DeleteModel(
            name='Alergen',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='IngredientVersion',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.AddField(
            model_name='recipe',
            name='_automatic_errors',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.recipeerror', verbose_name='Chyby'),
        ),
    ]
