# Generated by Django 4.1 on 2023-01-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0057_alter_recipeerror_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-status_changed', '-created'], 'permissions': [('change_recipe_status', 'Can change recipe status')]},
        ),
    ]
