# Generated by Django 4.1 on 2023-01-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0058_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-status_changed', '-created'], 'permissions': []},
        ),
    ]
