# Generated by Django 4.1 on 2023-04-02 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('sign', models.CharField(max_length=6, unique=True)),
                ('conversion_rate', models.DecimalField(decimal_places=6, max_digits=13, verbose_name='Konštanta na premenu na base_unit')),
                ('system', models.CharField(choices=[('METRIC', 'METRIC'), ('IMPERIAL', 'IMPERIAL')], default='METRIC', max_length=8)),
                ('property', models.CharField(choices=[('LENGTH', 'LENGTH'), ('MASS', 'MASS'), ('VOLUME', 'VOLUME'), ('NUMBER', 'NUMBER')], default='MASS', max_length=8)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sub_units', to='utils.unit')),
            ],
        ),
    ]
