# Generated by Django 4.1 on 2023-02-02 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import management.models.affix
import management.models.ingredients


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergen',
            fields=[
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Kód')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Pridajte ikonku', null=True, upload_to=management.models.affix.Attribute.icon_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Pridajte ikonku', null=True, upload_to=management.models.affix.Diet.icon_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('name', models.CharField(help_text='Názov ingrediencie', max_length=31, unique=True, verbose_name='Názov')),
                ('img', models.ImageField(blank=True, default=None, help_text='Pridajte obrazok ku ingrediencií', null=True, upload_to=management.models.ingredients.Ingredient.img_upload_to, verbose_name='Obrázok')),
                ('alergens', models.ManyToManyField(blank=True, default=None, help_text='Zvolte všetky alergény', related_name='ingredients', to='management.alergen', verbose_name='Alergény')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='utils.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KitchenAccesory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Pridajte ikonku', null=True, upload_to=management.models.affix.KitchenAccesory.icon_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], default='inactive', editable=False, max_length=8)),
                ('status_changed', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Zmena statusu')),
                ('cost', models.FloatField(help_text='Zadajte cenu na zvolené množstvo zvolenej jednotky', verbose_name='Cena na jednotku')),
                ('source', models.CharField(help_text='Toto ešte bude raz foreign key na dodávatela', max_length=64, verbose_name='Dodávateľ')),
                ('_in_stock_amount', models.FloatField(default=0, editable=False, help_text='Automaticky vypočítané poďla IngredientStockChange', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Množstvo na sklade')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='versions', to='management.ingredient', verbose_name='Ingrediencia')),
            ],
            options={
                'ordering': ('created',),
                'permissions': [('change_ingredient_status', 'Can change ingredient status')],
            },
        ),
    ]
