# Generated by Django 4.1 on 2023-04-02 08:21

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import management.affix.models
import management.ingredients.models
import management.recipe_designs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergen',
            fields=[
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Kód')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Pridajte ikonku', null=True, upload_to=management.affix.models.Attribute.icon_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Pridajte ikonku', null=True, upload_to=management.affix.models.Diet.icon_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('name', models.CharField(help_text='Názov ingrediencie', max_length=31, unique=True, verbose_name='Názov')),
                ('extra_info', models.TextField(blank=True, default=None, help_text='Extra informácie o ingrediencii', null=True, verbose_name='Extra informácie')),
                ('img', models.ImageField(blank=True, default=None, help_text='Pridajte obrazok ku ingrediencií', null=True, upload_to=management.ingredients.models.Ingredient.img_upload_to, verbose_name='Obrázok')),
                ('alergens', models.ManyToManyField(blank=True, default=None, help_text='Zvolte všetky alergény', related_name='ingredients', to='management.alergen', verbose_name='Alergény')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='utils.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], default='inactive', editable=False, max_length=8)),
                ('status_changed', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Zmena statusu')),
                ('_cost', models.FloatField(blank=True, help_text='Zadajte cenu na zvolené množstvo zvolenej jednotky', null=True, validators=[django.core.validators.MinValueValidator(0, message='Cena musí byť kladná')], verbose_name='Cena na jednotku')),
                ('source', models.CharField(help_text='Toto ešte bude raz foreign key na dodávatela', max_length=64, verbose_name='Dodávateľ')),
                ('_in_stock_amount', models.FloatField(default=0, editable=False, help_text='Automaticky vypočítané poďla IngredientStockChange', validators=[django.core.validators.MinValueValidator(0, message='Množstvo musí byť kladné')], verbose_name='Množstvo na sklade')),
                ('expiration_period', models.IntegerField(default=7, help_text='Zadajte množstvo dní', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Expiračný čas')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='versions', to='management.ingredient', verbose_name='Ingrediencia')),
            ],
            options={
                'ordering': ('created',),
                'permissions': [('change_ingredient_status', 'Can change ingredient status')],
            },
        ),
        migrations.CreateModel(
            name='IngredientVersionStockChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-09)], verbose_name='Množstvo')),
                ('ingredient_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_changes', to='management.ingredientversion')),
                ('unit', models.ForeignKey(help_text='Zadajte jednotku', on_delete=django.db.models.deletion.PROTECT, to='utils.unit', verbose_name='Jednotka')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='KitchenAccesory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Pridajte ikonku', null=True, upload_to=management.affix.models.KitchenAccesory.icon_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('date', models.DateField(unique=True, verbose_name='Dátum')),
                ('_public', models.BooleanField(default=False, editable=False, help_text='Označuje, či je recept verejný.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RDError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RecipeDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], default='inactive', editable=False, max_length=8)),
                ('status_changed', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Zmena statusu')),
                ('name', models.CharField(max_length=63, verbose_name='Názov')),
                ('description', models.TextField(help_text='Zadajte stručný opis jedla', max_length=127, verbose_name='Opis jedla')),
                ('thumbnail', models.ImageField(blank=True, help_text='Pridajte thumbnail', null=True, upload_to=management.recipe_designs.models.RecipeDesign.thumbnail_upload_to)),
                ('exclusive_inheritance', models.BooleanField(default=True, help_text='Predchodca bude deaktivovaný až v momente, keď tento recept aktivujete.             Toto je vysoko odporúčané, nakoľko hrozia duplicitné recepty v prípade nezaškrtnutia.', verbose_name='Deaktivovať predchodcu?')),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Profesional')], help_text='Zadajte náročnosť', verbose_name='Náročnosť')),
                ('cooking_time', models.IntegerField(help_text='Zadajte dĺžku varenia od začiatku do hotového jedla v minútach', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(900)], verbose_name='Čas varenia')),
                ('active_cooking_time', models.IntegerField(help_text='Zadajte čas, ktorý je potrebné venovať sa vareniu', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(300)], verbose_name='Aktívny čas varenia')),
                ('description_finished', models.BooleanField(default=False, help_text='Odznačte, ak ešte treba opis jedla prerobiť/opraviť/skontrolovať', verbose_name='Opis finálne hotový')),
                ('steps_finished', models.BooleanField(default=False, help_text='Odznačte, ak ešte treba postup prerobiť/opraviť', verbose_name='Postup finálne hotový')),
                ('ingredients_finished', models.BooleanField(default=False, help_text='Odznačte, ak ešte treba ingrediencie prerobiť/opraviť', verbose_name='Ingrediencie finálne hotové')),
                ('todo', models.TextField(blank=True, help_text='Sem napíš všetko, čo ešte pre tento recept nie je hotové. Veci oddeluj enterom.', verbose_name='ToDo poznámka')),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='Predajná cena')),
                ('_automatic_errors', models.ManyToManyField(blank=True, related_name='recipes', to='management.rderror', verbose_name='Chyby')),
                ('attributes', models.ManyToManyField(blank=True, help_text='Zadajte všetky atribúty jedla', related_name='recipes', to='management.attribute', verbose_name='Attribúty')),
                ('created_by', models.ForeignKey(help_text='Zvolte seba', on_delete=django.db.models.deletion.PROTECT, related_name='created_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('diet', models.ManyToManyField(blank=True, help_text='Spadá tento recept do nejakých diet?', related_name='recipes', to='management.diet', verbose_name='Dieta')),
                ('predecessor', models.ForeignKey(blank=True, help_text='V prípade, že je tento recept iba pozmenený predchádzajúci, zvolte ktorý mu predchádzal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='management.recipedesign', verbose_name='Predchodca')),
                ('required_accessories', models.ManyToManyField(blank=True, help_text='Zadajte všetky potrebné kuchynské pomôcky', related_name='recipes', to='management.kitchenaccesory', verbose_name='Potrebné kuchynské náradie')),
            ],
            options={
                'ordering': ['-status_changed', '-created'],
                'permissions': [('change_recipe_status', 'Can change recipe status')],
            },
        ),
        migrations.CreateModel(
            name='RecipeInMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('cost', models.FloatField(blank=True, default=None, null=True, verbose_name='Reálne náklady')),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='Predajná cena')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='management.menu')),
                ('recipe_design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='management.recipedesign')),
            ],
            options={
                'unique_together': {('recipe_design', 'menu')},
            },
        ),
        migrations.CreateModel(
            name='IngredientVersionStockOrder',
            fields=[
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, parent_link=True, primary_key=True, related_name='ordered', serialize=False, to='management.ingredientversionstockchange')),
                ('description', models.TextField(blank=True, default=None, help_text='Zadajte popis pridania', null=True, verbose_name='Popis')),
                ('order_date', models.DateTimeField(help_text='Zadajte dátum a čas objednávky', verbose_name='Dátum objednávky')),
                ('delivery_date', models.DateTimeField(help_text='Zadajte dátum a čas dodania', verbose_name='Dátum dodania')),
                ('is_delivered', models.BooleanField(default=False, help_text='Zaškrtnite, ak bolo dodané', verbose_name='Bolo dodané')),
                ('expiration_date', models.DateField(help_text='Zadajte dátum a čas expirácie', verbose_name='Dátum expirácie')),
                ('is_expired', models.BooleanField(default=False, help_text='Zaškrtnite, ak expirovalo', verbose_name='Expirované')),
                ('cost', models.FloatField(help_text='Zadajte cenu', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena')),
                ('_in_stock_amount', models.FloatField(default=0, help_text='Zadajte množstvo na sklade', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Množstvo v sklade')),
            ],
            options={
                'ordering': ('-order_date', 'delivery_date', 'created'),
            },
            bases=('management.ingredientversionstockchange',),
        ),
        migrations.CreateModel(
            name='IngredientVersionStockRemove',
            fields=[
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, parent_link=True, primary_key=True, related_name='removed', serialize=False, to='management.ingredientversionstockchange')),
                ('reason', models.CharField(choices=[('expired', 'Vypršal termín spotreby'), ('went_bad', 'Pokazilo sa'), ('other', 'Iný dôvod')], default='other', help_text='Zvolte dôvod odobratia', max_length=20, verbose_name='Dôvod')),
                ('description', models.TextField(blank=True, default=None, help_text='Zadajte popis odobratia', null=True, verbose_name='Popis')),
                ('date', models.DateTimeField(default=datetime.datetime.now, help_text='Zadajte dátum odobratia', verbose_name='Dátum')),
            ],
            options={
                'ordering': ('created',),
            },
            bases=('management.ingredientversionstockchange',),
        ),
        migrations.CreateModel(
            name='RMIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('amount', models.FloatField(help_text='Zadajte množstvo danej potraviny na dve porcie', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Množstvo')),
                ('alternative_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='management.rmingredient')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_designs', to='management.ingredientversion')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='management.recipeinmenu')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.unit', verbose_name='Jednotka')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RDStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Poradie kroku')),
                ('text', models.TextField(verbose_name='Text')),
                ('thumbnail', models.ImageField(blank=True, help_text='Pridajte thumbnail', null=True, upload_to=management.recipe_designs.models.RDStep.upload_to)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='management.recipedesign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RDIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('amount', models.FloatField(help_text='Zadajte množstvo danej potraviny na dve porcie', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Množstvo')),
                ('alternative_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='management.rdingredient')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_designs', to='management.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='management.recipedesign')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.unit', verbose_name='Jednotka')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='recipedesign',
            constraint=models.CheckConstraint(check=models.Q(('cooking_time__gte', models.F('active_cooking_time'))), name='cooking_time_gte_active_cooking_time', violation_error_message='Čas varenia musí byť väčší alebo rovný aktívnemu času varenia'),
        ),
    ]
