# Generated by Django 4.1 on 2023-03-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_ingredientstockchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='extra_info',
            field=models.TextField(blank=True, default=None, help_text='Extra informácie o ingrediencii', null=True, verbose_name='Extra informácie'),
        ),
    ]
