# Generated by Django 4.1 on 2023-03-10 18:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('management', '0004_ingredient_extra_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientVersionStockChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Množstvo')),
                ('ingredient_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_changes', to='management.ingredientversion')),
                ('unit', models.ForeignKey(blank=True, help_text='Zadajte jednotku', on_delete=django.db.models.deletion.PROTECT, to='utils.unit', verbose_name='Jednotka')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientVersionStockOrder',
            fields=[
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='extension', serialize=False, to='management.ingredientversionstockchange')),
                ('description', models.TextField(blank=True, default=None, help_text='Zadajte popis pridania', null=True, verbose_name='Popis')),
                ('order_date', models.DateTimeField(help_text='Zadajte dátum a čas objednávky', verbose_name='Dátum objednávky')),
                ('delivery_date', models.DateTimeField(help_text='Zadajte dátum a čas dodania', verbose_name='Dátum dodania')),
                ('is_delivered', models.BooleanField(default=False, help_text='Zaškrtnite, ak bolo dodané', verbose_name='Bolo dodané')),
            ],
            options={
                'abstract': False,
            },
            bases=('management.ingredientversionstockchange',),
        ),
        migrations.CreateModel(
            name='IngredientVersionStockRemove',
            fields=[
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, parent_link=True, primary_key=True, related_name='removed', serialize=False, to='management.ingredientversionstockchange')),
                ('reason', models.CharField(choices=[('expired', 'Vypršal termín spotreby'), ('went_bad', 'Pokazilo sa'), ('other', 'Iný dôvod')], default='other', help_text='Zvolte dôvod odobratia', max_length=20, verbose_name='Dôvod')),
                ('description', models.TextField(blank=True, default=None, help_text='Zadajte popis odobratia', null=True, verbose_name='Popis')),
            ],
            bases=('management.ingredientversionstockchange',),
        ),
        migrations.DeleteModel(
            name='IngredientStockChange',
        ),
        migrations.AddConstraint(
            model_name='ingredientversionstockremove',
            constraint=models.CheckConstraint(check=models.Q(('reason__exact', 'other'), ('description__isnull', True)), name='management_ingredientversionstockremove_other_reason_has_no_description'),
        ),
    ]
