# Generated by Django 4.1 on 2023-03-12 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_ingredientversionstockchange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientversion',
            name='cost',
            field=models.FloatField(help_text='Zadajte cenu na zvolené množstvo zvolenej jednotky', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena na jednotku'),
        ),
    ]
