# Generated by Django 4.1 on 2023-03-12 10:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('management', '0006_alter_ingredientversion_cost'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientversionstockremove',
            name='management_ingredientversionstockremove_other_reason_has_no_description',
        ),
        migrations.AlterField(
            model_name='ingredientversion',
            name='_in_stock_amount',
            field=models.FloatField(default=0, editable=False, help_text='Automaticky vypočítané poďla IngredientStockChange', validators=[django.core.validators.MinValueValidator(0, message='Množstvo musí byť kladné')], verbose_name='Množstvo na sklade'),
        ),
        migrations.AlterField(
            model_name='ingredientversion',
            name='cost',
            field=models.FloatField(help_text='Zadajte cenu na zvolené množstvo zvolenej jednotky', validators=[django.core.validators.MinValueValidator(0, message='Cena musí byť kladná')], verbose_name='Cena na jednotku'),
        ),
        migrations.AlterField(
            model_name='ingredientversionstockchange',
            name='unit',
            field=models.ForeignKey(help_text='Zadajte jednotku', on_delete=django.db.models.deletion.PROTECT, to='utils.unit', verbose_name='Jednotka'),
        ),
        migrations.AddConstraint(
            model_name='ingredientversionstockremove',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('description__isnull', False), ('reason', 'other')), models.Q(('reason', 'other'), _negated=True), _connector='OR'), name='management_ingredientversionstockremove_other_reason_has_no_description'),
        ),
    ]
