# Generated by Django 4.1 on 2023-03-16 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_ingredientversionstockremove_management_ingredientversionstockremove_other_reason_has_no_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientversionstockchange',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='ingredientversionstockorder',
            options={'ordering': ('order_date', 'delivery_date', 'created')},
        ),
        migrations.AlterModelOptions(
            name='ingredientversionstockremove',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='ingredientversion',
            name='expiration_period',
            field=models.IntegerField(default=7, help_text='Zadajte množstvo dní', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Expiračný čas'),
        ),
        migrations.AlterField(
            model_name='ingredientversionstockorder',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ordered', serialize=False, to='management.ingredientversionstockchange'),
        ),
    ]
