# Generated by Django 4.1 on 2023-03-17 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_ingredientversionstockremove_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientversionstockorder',
            name='expiration_date',
            field=models.DateField(default=datetime.date.today, help_text='Zadajte dátum a čas expirácie', verbose_name='Dátum expirácie'),
            preserve_default=False,
        ),
    ]
