# Generated by Django 4.1 on 2023-03-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_ingredientversionstockorder_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientversionstockorder',
            name='is_expired',
            field=models.BooleanField(default=False, help_text='Zaškrtnite, ak expirovalo', verbose_name='Expirované'),
        ),
    ]
