# Generated by Django 4.1 on 2023-03-17 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_ingredientversionstockorder_is_expired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientversionstockorder',
            options={'ordering': ('-order_date', 'delivery_date', 'created')},
        ),
        migrations.AddField(
            model_name='ingredientversionstockorder',
            name='cost',
            field=models.FloatField(default=1, help_text='Zadajte cenu', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientversion',
            name='cost',
            field=models.FloatField(blank=True, help_text='Zadajte cenu na zvolené množstvo zvolenej jednotky', null=True, validators=[django.core.validators.MinValueValidator(0, message='Cena musí byť kladná')], verbose_name='Cena na jednotku'),
        ),
    ]
