# Generated by Django 4.1 on 2023-03-17 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_ingredientversionstockorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientversionstockorder',
            name='in_stock_amount',
            field=models.FloatField(default=0, help_text='Zadajte množstvo na sklade', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Množstvo v sklade'),
        ),
    ]
