# Generated by Django 4.1 on 2023-03-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_rename_in_stock_amount_ingredientversionstockorder__in_stock_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientversion',
            old_name='cost',
            new_name='_cost',
        ),
    ]
