# Generated by Django 4.1 on 2023-03-18 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_rename_cost_ingredientversion__cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientversionstockchange',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-09)], verbose_name='Množstvo'),
        ),
    ]
