# Generated by Django 4.1 on 2023-03-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_ingredientversionstockchange_amount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientversionstockorder',
            name='management_ingredientversionstockorder_in_stock_amount_is_0_if_is_delivered_is_false',
        ),
        migrations.RemoveConstraint(
            model_name='ingredientversionstockremove',
            name='management_ingredientversionstockremove_other_reason_has_no_description',
        ),
    ]
