# Generated by Django 4.1 on 2023-03-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('management', '0017_remove_ingredientversionstockorder_management_ingredientversionstockorder_in_stock_amount_is_0_if_is'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdingredient',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='utils.unit', verbose_name='Jednotka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rmingredient',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='utils.unit', verbose_name='Jednotka'),
            preserve_default=False,
        ),
    ]
