# Generated by Django 4.1 on 2023-03-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_rdingredient_unit_rmingredient_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rdingredient',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rmingredient',
            unique_together=set(),
        ),
    ]
