# Generated by Django 4.1 on 2022-11-05 13:13

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=150, verbose_name='Meno')),
                ('last_name', models.CharField(max_length=150, verbose_name='Priezvisko')),
                ('pronoun', models.CharField(choices=[('male', 'Mužský rod'), ('female', 'Ženský rod')], max_length=16, verbose_name='Oslovovanie')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(default='+421', help_text='Môže byť použité počas doručovania', max_length=20, verbose_name='Telefónne číslo')),
                ('newsletter', models.BooleanField(default=True)),
                ('terms_conditions', models.BooleanField()),
                ('is_email_valid', models.BooleanField(default=False)),
                ('is_payment_valid', models.BooleanField(default=False)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('default_num_portions', models.IntegerField(choices=[(2, 2), (4, 4), (6, 6)], default=4, help_text='Koľko vás bude pravidelne jedávať?', verbose_name='Počet porcií')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Domov', max_length=32, verbose_name='Názov adresy')),
                ('address', models.CharField(help_text='Nezabudnite pridať číslo domu', max_length=128, verbose_name='Adresa a číslo domu')),
                ('note', models.TextField(blank=True, help_text='(zvonček, poschodie, ...)', max_length=256, verbose_name='Poznámka pre kuriéra')),
                ('city', models.CharField(max_length=100, verbose_name='Mesto')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='Okres')),
                ('postal', models.CharField(max_length=6, verbose_name='PSČ')),
                ('country', models.CharField(blank=True, max_length=32, verbose_name='Krajina')),
                ('coordinates', models.CharField(max_length=64)),
                ('primary', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
