# Generated by Django 4.1 on 2022-10-25 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Domov', help_text='Názov, pod ktorým uložíme túto adresu', max_length=32, verbose_name='Názov adresy')),
                ('address', models.CharField(help_text='Nezabudnite pridať číslo domu', max_length=128, verbose_name='Adresa a číslo domu')),
                ('note', models.TextField(blank=True, help_text='(zvonček, poschodie, ...)', max_length=256, verbose_name='Poznámka pre kuriéra')),
                ('city', models.CharField(max_length=100, verbose_name='Mesto')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='Okres')),
                ('postal', models.CharField(max_length=6, verbose_name='PSČ')),
                ('country', models.CharField(blank=True, max_length=32, verbose_name='Krajina')),
                ('coordinates', models.CharField(max_length=64)),
                ('primary', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
