# Generated by Django 4.1 on 2022-11-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alergies',
            field=models.ManyToManyField(blank=True, default=None, help_text='Máte nejaké alergie? Povedzte nám o nich teraz a my vám nikdy automaticky neobjednáme recept obsahujúci daný alergén.', related_name='users', to='recipes.alergen', verbose_name='Alergie'),
        ),
        migrations.AddField(
            model_name='user',
            name='diet',
            field=models.ManyToManyField(blank=True, default=None, help_text='Máte nejaké diety? Pri automatickom objednávanií vám budeme vyberať iba z jednál, ktoré spadajú do vašej diety.', related_name='users', to='recipes.diet', verbose_name='Diety'),
        ),
        migrations.AddField(
            model_name='user',
            name='food_preferences',
            field=models.ManyToManyField(blank=True, help_text='Pri zvolení automatického objednávania vám vyberieme jedlá, ktoré budú zdielať najviac atríbutov s vašimi preferenciami.', related_name='users', to='recipes.attribute', verbose_name='Preferencie'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
