# Generated by Django 4.1 on 2023-02-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alergies',
            field=models.ManyToManyField(blank=True, default=None, help_text='Máte nejaké alergie? Povedzte nám o nich teraz a my vám nikdy automaticky neobjednáme recept obsahujúci daný alergén.', related_name='users', to='management.alergen', verbose_name='Alergie'),
        ),
        migrations.AddField(
            model_name='user',
            name='diet',
            field=models.ManyToManyField(blank=True, default=None, help_text='Máte nejaké diety? Pri automatickom objednávanií vám budeme vyberať iba z jednál, ktoré spadajú do vašej diety.', related_name='users', to='management.diet', verbose_name='Diety'),
        ),
        migrations.AddField(
            model_name='user',
            name='food_preferences',
            field=models.ManyToManyField(blank=True, help_text='Pri zvolení automatického objednávania vám vyberieme jedlá, ktoré budú zdielať najviac atríbutov s vašimi preferenciami.', related_name='users', to='management.attribute', verbose_name='Preferencie'),
        ),
        migrations.AddField(
            model_name='user',
            name='kitchen_accesories',
            field=models.ManyToManyField(blank=True, default=None, help_text='Zvolte všetko kuchynské náradie, ktoré máte doma. Pri automatickom objednávanií vám budeme vyberať jedlá, ktoré sa dajú pripraviť s vašim kuchynským náradím.', related_name='users', to='management.kitchenaccesory', verbose_name='Kuchynské náradie'),
        ),
    ]
