# Generated by Django 4.1 on 2023-01-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diet',
            field=models.ManyToManyField(blank=True, default=None, help_text='Máte nejaké diety? Pri automatickom objednávanií vám budeme vyberať iba z jednál, ktoré spadajú do vašej diety.', related_name='users', to='recipes.diet', verbose_name='Diety'),
        ),
        migrations.AddField(
            model_name='user',
            name='food_preferences',
            field=models.ManyToManyField(blank=True, help_text='Pri zvolení automatického objednávania vám vyberieme jedlá, ktoré budú zdielať najviac atríbutov s vašimi preferenciami.', related_name='users', to='recipes.attribute', verbose_name='Preferencie'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='kitchen_accesories',
            field=models.ManyToManyField(blank=True, default=None, help_text='Zvolte všetko kuchynské náradie, ktoré máte doma. Pri automatickom objednávanií vám budeme vyberať jedlá, ktoré sa dajú pripraviť s vašim kuchynským náradím.', related_name='users', to='recipes.kitchenaccesory', verbose_name='Kuchynské náradie'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('_is_payment_valid', True), ('_is_subscribed', True)), ('_is_subscribed', False), _connector='OR'), name='Payment is required for subscription'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('_is_email_valid', True), ('_is_payment_valid', True)), ('_is_payment_valid', False), _connector='OR'), name='Email confirmation is required for adding payment method'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('_is_subscribed', True), ('is_active', True)), ('_is_subscribed', False), _connector='OR'), name='Being active is required for subscription'),
        ),
    ]
