# Generated by Django 4.1 on 2022-11-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_valid',
            field=models.BooleanField(default=False, help_text='Designates whether this user has confirmed email. '),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_payment_valid',
            field=models.BooleanField(default=False, help_text='Designates whether this user has a valid payment option. '),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False, help_text='Designates whether this user is subscribed, has automatic payments turned on. '),
        ),
    ]
