# Generated by Django 4.1 on 2022-11-01 14:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_diet_name'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(default='Domov', max_length=32, verbose_name='Názov adresy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='diet',
            field=models.ManyToManyField(default=accounts.models.default_diet, related_name='users', to='recipes.diet'),
        ),
    ]
