# Generated by Django 4.1 on 2022-10-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diets',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.diet'),
        ),
    ]
