# Generated by Django 4.1 on 2022-11-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_diet_name'),
        ('accounts', '0003_alter_address_name_alter_user_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diet',
            field=models.ManyToManyField(blank=True, default=None, related_name='users', to='recipes.diet'),
        ),
    ]
