# Generated by Django 4.1 on 2022-11-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_diet_name'),
        ('accounts', '0004_alter_user_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alergies',
            field=models.ManyToManyField(blank=True, default=None, help_text='Máte nejaké alergie? Povedzte nám o nich teraz a my vám nikdy automaticky neobjednáme recept obsahujúci daný alergén.', related_name='users', to='recipes.alergen', verbose_name='Alergie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_num_portions',
            field=models.IntegerField(choices=[(2, 2), (4, 4), (6, 6)], default=4, help_text='Koľko vás bude pravidelne jedávať?', verbose_name='Počet porcií'),
        ),
        migrations.AlterField(
            model_name='user',
            name='diet',
            field=models.ManyToManyField(blank=True, default=None, help_text='Máte nejaké diety? Pri automatickom objednávanií vám budeme vyberať iba z jednál, ktoré spadajú do vašej diety.', related_name='users', to='recipes.diet', verbose_name='Diety'),
        ),
        migrations.AlterField(
            model_name='user',
            name='food_preferences',
            field=models.ManyToManyField(blank=True, default=None, help_text='Pri zvolení automatického objednávania vám vyberieme jedlá, ktoré budú zdielať najviac atríbutov s vašimi preferenciami.', related_name='users', to='recipes.attribute', verbose_name='Preferencie'),
        ),
    ]
