# Generated by Django 4.1 on 2022-11-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_payment is required for subscription_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='payment is required for subscription',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_payment_valid', True), ('is_subscribed', True)), ('is_subscribed', False), _connector='OR'), name='Payment is required for subscription'),
        ),
    ]
