# Generated by Django 4.1 on 2022-11-04 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_alergies_alter_user_default_num_portions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='pronoun',
            field=models.CharField(choices=[('male', 'Mužský rod'), ('female', 'Ženský rod')], max_length=16, verbose_name='Oslovovanie'),
        ),
    ]
