# Generated by Django 4.1 on 2022-10-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_alergies_user_food_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='diets',
        ),
        migrations.AddField(
            model_name='user',
            name='diet',
            field=models.ManyToManyField(related_name='users', to='accounts.diet'),
        ),
    ]
