# Generated by Django 4.1 on 2022-11-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_payment is required for subscription_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_active', True), ('is_subscribed', True)), ('is_subscribed', False), _connector='OR'), name='Being active is required for subscription'),
        ),
    ]
