# Generated by Django 4.1 on 2022-11-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_being active is required for subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_pickup',
            field=models.BooleanField(default=False, help_text='Zaškrtnite, ak si želáte objednávky vyzdvihovať osobne u nás v kamennej predajni.', verbose_name='Osobné vyzdvihovanie'),
        ),
    ]
