# Generated by Django 4.1 on 2022-10-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_diet_alter_recipe_diet'),
        ('accounts', '0006_remove_user_diets_user_diet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diet',
        ),
        migrations.AlterField(
            model_name='user',
            name='diet',
            field=models.ManyToManyField(related_name='users', to='recipes.diet'),
        ),
    ]
