# Generated by Django 4.1 on 2022-11-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_default_pickup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_email_valid',
            new_name='_is_email_valid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_payment_valid',
            new_name='_is_payment_valid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_subscribed',
            new_name='_is_subscribed',
        ),
    ]
