# Generated by Django 4.1 on 2022-11-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_is_email_valid_user__is_email_valid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='Email confirmation is required for adding payment method',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='Payment is required for subscription',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='Being active is required for subscription',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('_is_payment_valid', True), ('_is_subscribed', True)), ('_is_subscribed', False), _connector='OR'), name='Payment is required for subscription'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('_is_email_valid', True), ('_is_payment_valid', True)), ('_is_payment_valid', False), _connector='OR'), name='Email confirmation is required for adding payment method'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('_is_subscribed', True), ('is_active', True)), ('_is_subscribed', False), _connector='OR'), name='Being active is required for subscription'),
        ),
    ]
