# Generated by Django 4.1 on 2023-01-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('accounts', '0009_remove_user_email confirmation is required for adding payment method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alergies',
            field=models.ManyToManyField(blank=True, default=None, help_text='Máte nejaké alergie? Povedzte nám o nich teraz a my vám nikdy automaticky neobjednáme recept obsahujúci daný alergén.', related_name='users', to='ingredients.alergen', verbose_name='Alergie'),
        ),
    ]
