name: Deploy to GAE

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types:
      - closed

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v1"

      # Example of using the output
      - id: "test"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
