name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run SQL Proxy
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          instance: mandalinka-382516:europe-west6:mandalinka
      - name: test
        run: |
          python manage.py test
      # Write success as a comment into the pull request
      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ success() && github.event_name == 'pull_request' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :white_check_mark: All tests passed!
      # Write failure as a comment into the pull request
      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ failure() && github.event_name == 'pull_request' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :x: Some tests failed!
